import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        // WebCore Audit Brand Colors (from logo - vibrant)
        "wc-cyan": {
          50: "#E8F7FC",
          100: "#C5EDF8",
          200: "#91DCF3",
          300: "#5BC0EB",
          400: "#4AA8D8",
          500: "#3B96C9",
          600: "#2D7AAA",
          700: "#1F5E8B",
          DEFAULT: "#5BC0EB",
        },
        "wc-blue": {
          50: "#E6F1FB",
          100: "#C2DEF5",
          200: "#7FBCEB",
          300: "#4A9EE0",
          400: "#2E86DE",
          500: "#2574C4",
          600: "#1E5AA8",
          700: "#1A4B8C",
          800: "#143A6E",
          900: "#0E2A50",
          DEFAULT: "#2E86DE",
        },
        "wc-green": {
          50: "#F4FCE3",
          100: "#E5F7B8",
          200: "#C8F06D",
          300: "#B8E233",
          400: "#7ED321",
          500: "#5FB818",
          600: "#4CAF50",
          700: "#3D8B40",
          800: "#2E6830",
          900: "#1F4520",
          DEFAULT: "#7ED321",
        },
        "wc-dark": {
          50: "#E8EEF5",
          100: "#C5D3E5",
          200: "#8FA8C9",
          300: "#5A7DAD",
          400: "#2E5891",
          500: "#1E4175",
          600: "#183561",
          700: "#12294D",
          800: "#0C1C39",
          900: "#060E25",
          DEFAULT: "#1E4175",
        },
        // Legacy colors
        "text-primary": "#FFFFFF",
        "text-secondary": "#A1A1A1",
        "text-tertiary": "#666666",
        "accent-blue": "#3B82F6",
        "accent-blue-hover": "#2563EB",
        success: "#22C55E",
        warning: "#F59E0B",
        critical: "#EF4444",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "-apple-system", "system-ui", "sans-serif"],
        condensed: ["var(--font-inter-tight)", "var(--font-inter)", "-apple-system", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains)", "'Courier New'", "monospace"],
      },
      fontSize: {
        "hero": ["3.5rem", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "section": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "card-title": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "subsection": ["1.125rem", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body": ["0.9375rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "caption": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "3xl": "64px",
        "4xl": "80px",
        "5xl": "120px",
      },
      borderRadius: {
        "sm": "6px",
        "md": "10px",
        "lg": "14px",
        "xl": "20px",
        "2xl": "24px",
        "full": "9999px",
      },
      boxShadow: {
        "subtle": "0 1px 2px rgba(0,0,0,0.2)",
        "elevated": "0 4px 6px rgba(0,0,0,0.1), 0 2px 4px rgba(0,0,0,0.06)",
        "modal": "0 25px 50px rgba(0,0,0,0.25), 0 10px 20px rgba(0,0,0,0.15)",
        "glow": "0 0 40px rgba(59,130,246,0.15)",
        "glow-lg": "0 0 60px rgba(59,130,246,0.2)",
        "3d-icon": "0 10px 30px rgba(0,0,0,0.3), 0 5px 15px rgba(0,0,0,0.2)",
        "inner-glow": "inset 0 1px 1px rgba(255,255,255,0.05), inset 0 -1px 1px rgba(0,0,0,0.1)",
        "glass": "0 4px 30px rgba(0,0,0,0.3), inset 0 1px 1px rgba(255,255,255,0.05)",
        "button-hover": "0 4px 12px rgba(59,130,246,0.3)",
      },
      backdropBlur: {
        "glass": "20px",
        "glass-heavy": "40px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "gradient-x": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "shimmer": "shimmer 1.5s infinite",
        "fade-in": "fade-in 0.3s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "gradient-x": "gradient-x 3s ease infinite",
      },
      transitionTimingFunction: {
        "smooth": "cubic-bezier(0.4, 0, 0.2, 1)",
        "enter": "cubic-bezier(0, 0, 0.2, 1)",
        "exit": "cubic-bezier(0.4, 0, 1, 1)",
        "bounce": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
