import { DEFAULT_CATEGORY_WEIGHTS } from '@/lib/types/audit';

export interface WebsiteTypeConfig {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  categoryWeights: Record<string, number>;
  focusAreas: string[];
  bestPractices: string[];
}

export const WEBSITE_TYPES: WebsiteTypeConfig[] = [
  // Creative & Personal
  {
    id: 'portfolio',
    name: 'Portfolio',
    slug: 'portfolio',
    description: 'Personal or creative portfolios showcasing work, projects, and skills',
    icon: 'Briefcase',
    categoryWeights: {
      'Business Overview': 0.8,
      'Technical Foundation': 1.0,
      'Brand & Messaging': 1.5,
      'User Experience': 1.3,
      'Traffic Readiness': 0.6,
      'Security': 0.6,
      'Content Strategy': 0.7,
      'Conversion & Engagement': 0.6,
      'Social & Multimedia': 1.2,
      'Trust & Credibility': 1.0,
    },
    focusAreas: ['Visual Design', 'Project Showcase', 'Personal Branding', 'Contact Information', 'Work Samples'],
    bestPractices: ['High-quality project images', 'Clear project descriptions', 'Easy navigation between projects', 'Prominent contact information', 'Mobile-responsive gallery'],
  },
  {
    id: 'personal-brand',
    name: 'Personal Brand',
    slug: 'personal-brand',
    description: 'Personal websites for thought leaders, influencers, and professionals',
    icon: 'User',
    categoryWeights: {
      'Business Overview': 1.0,
      'Technical Foundation': 0.9,
      'Brand & Messaging': 1.6,
      'User Experience': 1.1,
      'Traffic Readiness': 1.0,
      'Security': 0.6,
      'Content Strategy': 1.3,
      'Conversion & Engagement': 1.0,
      'Social & Multimedia': 1.4,
      'Trust & Credibility': 1.2,
    },
    focusAreas: ['Personal Story', 'Social Proof', 'Speaking/Services', 'Content Hub', 'Newsletter'],
    bestPractices: ['Authentic personal story', 'Professional headshot', 'Social media integration', 'Clear value proposition', 'Email list building'],
  },

  // Business & Services
  {
    id: 'saas',
    name: 'SaaS',
    slug: 'saas',
    description: 'Software as a Service products with subscription-based models',
    icon: 'Cloud',
    categoryWeights: {
      'Business Overview': 1.2,
      'Technical Foundation': 1.4,
      'Brand & Messaging': 1.2,
      'User Experience': 1.3,
      'Traffic Readiness': 1.2,
      'Security': 1.5,
      'Content Strategy': 1.0,
      'Conversion & Engagement': 1.5,
      'Social & Multimedia': 0.6,
      'Trust & Credibility': 1.3,
    },
    focusAreas: ['Pricing Clarity', 'Feature Comparison', 'Free Trial/Demo', 'Security & Compliance', 'Customer Testimonials'],
    bestPractices: ['Clear pricing tiers', 'Feature comparison tables', 'Prominent CTA for trial/demo', 'Security badges and certifications', 'Customer success stories'],
  },
  {
    id: 'agency',
    name: 'Agency',
    slug: 'agency',
    description: 'Marketing, design, development, or consulting agencies',
    icon: 'Building',
    categoryWeights: {
      'Business Overview': 1.3,
      'Technical Foundation': 1.2,
      'Brand & Messaging': 1.4,
      'User Experience': 1.2,
      'Traffic Readiness': 1.0,
      'Security': 0.8,
      'Content Strategy': 1.2,
      'Conversion & Engagement': 1.3,
      'Social & Multimedia': 0.8,
      'Trust & Credibility': 1.4,
    },
    focusAreas: ['Case Studies', 'Service Offerings', 'Team Expertise', 'Client Logos', 'Results & Metrics'],
    bestPractices: ['Detailed case studies with results', 'Clear service descriptions', 'Team bios and expertise', 'Client testimonials', 'Easy contact/quote request'],
  },
  {
    id: 'startup',
    name: 'Startup',
    slug: 'startup',
    description: 'Early-stage companies and startup landing pages',
    icon: 'Rocket',
    categoryWeights: {
      'Business Overview': 1.3,
      'Technical Foundation': 1.1,
      'Brand & Messaging': 1.5,
      'User Experience': 1.2,
      'Traffic Readiness': 1.0,
      'Security': 1.0,
      'Content Strategy': 0.8,
      'Conversion & Engagement': 1.6,
      'Social & Multimedia': 0.7,
      'Trust & Credibility': 1.1,
    },
    focusAreas: ['Value Proposition', 'Problem/Solution', 'Early Traction', 'Team Credibility', 'Waitlist/Beta Signup'],
    bestPractices: ['Clear problem statement', 'Compelling solution pitch', 'Show early traction/metrics', 'Founder credibility', 'Easy signup process'],
  },
  {
    id: 'consulting',
    name: 'Consulting',
    slug: 'consulting',
    description: 'Professional consulting and advisory services',
    icon: 'Users',
    categoryWeights: {
      'Business Overview': 1.4,
      'Technical Foundation': 1.0,
      'Brand & Messaging': 1.3,
      'User Experience': 1.1,
      'Traffic Readiness': 0.9,
      'Security': 0.8,
      'Content Strategy': 1.3,
      'Conversion & Engagement': 1.2,
      'Social & Multimedia': 0.7,
      'Trust & Credibility': 1.5,
    },
    focusAreas: ['Expertise Areas', 'Methodology', 'Client Results', 'Thought Leadership', 'Contact Process'],
    bestPractices: ['Demonstrate expertise clearly', 'Show methodology/process', 'Quantified client results', 'Publish thought leadership content', 'Easy consultation booking'],
  },

  // E-commerce & Retail
  {
    id: 'e-commerce',
    name: 'E-commerce',
    slug: 'e-commerce',
    description: 'Online stores selling physical or digital products',
    icon: 'ShoppingCart',
    categoryWeights: {
      'Business Overview': 0.8,
      'Technical Foundation': 1.4,
      'Brand & Messaging': 1.0,
      'User Experience': 1.5,
      'Traffic Readiness': 1.3,
      'Security': 1.5,
      'Content Strategy': 0.8,
      'Conversion & Engagement': 1.5,
      'Social & Multimedia': 0.8,
      'Trust & Credibility': 1.4,
    },
    focusAreas: ['Product Pages', 'Checkout Flow', 'Payment Security', 'Shipping Information', 'Return Policy'],
    bestPractices: ['High-quality product images', 'Clear pricing and shipping costs', 'Trust badges at checkout', 'Easy cart management', 'Multiple payment options'],
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    slug: 'marketplace',
    description: 'Multi-vendor marketplaces and directory platforms',
    icon: 'Store',
    categoryWeights: {
      'Business Overview': 1.1,
      'Technical Foundation': 1.4,
      'Brand & Messaging': 1.0,
      'User Experience': 1.5,
      'Traffic Readiness': 1.3,
      'Security': 1.4,
      'Content Strategy': 0.9,
      'Conversion & Engagement': 1.3,
      'Social & Multimedia': 0.7,
      'Trust & Credibility': 1.3,
    },
    focusAreas: ['Search & Discovery', 'Seller Profiles', 'Review System', 'Payment Security', 'Category Navigation'],
    bestPractices: ['Powerful search functionality', 'Verified seller badges', 'Robust review system', 'Secure payment processing', 'Clear category structure'],
  },

  // Content & Media
  {
    id: 'blog-media',
    name: 'Blog / Media',
    slug: 'blog-media',
    description: 'Content-focused sites like blogs, news, or media publications',
    icon: 'Newspaper',
    categoryWeights: {
      'Business Overview': 0.6,
      'Technical Foundation': 1.2,
      'Brand & Messaging': 1.0,
      'User Experience': 1.2,
      'Traffic Readiness': 1.5,
      'Security': 0.7,
      'Content Strategy': 1.5,
      'Conversion & Engagement': 1.0,
      'Social & Multimedia': 1.3,
      'Trust & Credibility': 0.9,
    },
    focusAreas: ['Content Organization', 'SEO Optimization', 'Reading Experience', 'Social Sharing', 'Newsletter Signup'],
    bestPractices: ['Clear content categories', 'Fast page load times', 'Easy-to-read typography', 'Social sharing buttons', 'Email subscription option'],
  },
  {
    id: 'membership',
    name: 'Membership / Community',
    slug: 'membership',
    description: 'Membership sites, online communities, and subscription content',
    icon: 'Users',
    categoryWeights: {
      'Business Overview': 1.1,
      'Technical Foundation': 1.3,
      'Brand & Messaging': 1.2,
      'User Experience': 1.3,
      'Traffic Readiness': 1.0,
      'Security': 1.4,
      'Content Strategy': 1.2,
      'Conversion & Engagement': 1.4,
      'Social & Multimedia': 1.0,
      'Trust & Credibility': 1.2,
    },
    focusAreas: ['Member Benefits', 'Community Features', 'Content Preview', 'Pricing Tiers', 'Member Testimonials'],
    bestPractices: ['Clear membership benefits', 'Preview of exclusive content', 'Active community showcase', 'Easy signup process', 'Member success stories'],
  },

  // Local & Service Businesses
  {
    id: 'local-business',
    name: 'Local Business',
    slug: 'local-business',
    description: 'Brick-and-mortar businesses serving local customers',
    icon: 'MapPin',
    categoryWeights: {
      'Business Overview': 1.4,
      'Technical Foundation': 1.0,
      'Brand & Messaging': 1.1,
      'User Experience': 1.1,
      'Traffic Readiness': 1.2,
      'Security': 0.7,
      'Content Strategy': 0.7,
      'Conversion & Engagement': 1.2,
      'Social & Multimedia': 0.9,
      'Trust & Credibility': 1.4,
    },
    focusAreas: ['Location & Hours', 'Contact Information', 'Google Business Profile', 'Reviews & Ratings', 'Services/Menu'],
    bestPractices: ['Prominent address and phone number', 'Embedded Google Maps', 'Customer reviews displayed', 'Clear business hours', 'Mobile click-to-call'],
  },
  {
    id: 'restaurant',
    name: 'Restaurant / Food Service',
    slug: 'restaurant',
    description: 'Restaurants, cafes, bars, and food service businesses',
    icon: 'UtensilsCrossed',
    categoryWeights: {
      'Business Overview': 1.2,
      'Technical Foundation': 1.1,
      'Brand & Messaging': 1.2,
      'User Experience': 1.3,
      'Traffic Readiness': 1.1,
      'Security': 0.8,
      'Content Strategy': 0.8,
      'Conversion & Engagement': 1.3,
      'Social & Multimedia': 1.2,
      'Trust & Credibility': 1.2,
    },
    focusAreas: ['Menu Display', 'Online Ordering', 'Reservations', 'Location & Hours', 'Food Photography'],
    bestPractices: ['Appetizing food photography', 'Easy-to-read menu with prices', 'Online ordering integration', 'Reservation system', 'Clear location and hours'],
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    slug: 'real-estate',
    description: 'Real estate agents, brokers, and property listings',
    icon: 'Home',
    categoryWeights: {
      'Business Overview': 1.2,
      'Technical Foundation': 1.2,
      'Brand & Messaging': 1.1,
      'User Experience': 1.4,
      'Traffic Readiness': 1.2,
      'Security': 0.9,
      'Content Strategy': 1.0,
      'Conversion & Engagement': 1.3,
      'Social & Multimedia': 1.0,
      'Trust & Credibility': 1.4,
    },
    focusAreas: ['Property Search', 'Listing Quality', 'Agent Profiles', 'Market Information', 'Contact Options'],
    bestPractices: ['IDX/MLS integration', 'High-quality property photos', 'Virtual tours', 'Neighborhood information', 'Easy inquiry forms'],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    slug: 'healthcare',
    description: 'Medical practices, clinics, and healthcare providers',
    icon: 'Heart',
    categoryWeights: {
      'Business Overview': 1.3,
      'Technical Foundation': 1.2,
      'Brand & Messaging': 1.0,
      'User Experience': 1.3,
      'Traffic Readiness': 1.0,
      'Security': 1.5,
      'Content Strategy': 1.1,
      'Conversion & Engagement': 1.2,
      'Social & Multimedia': 0.6,
      'Trust & Credibility': 1.5,
    },
    focusAreas: ['Services Offered', 'Provider Credentials', 'Patient Portal', 'Appointment Booking', 'Insurance Information'],
    bestPractices: ['HIPAA compliance indicators', 'Provider credentials displayed', 'Easy appointment scheduling', 'Patient testimonials', 'Clear service descriptions'],
  },
  {
    id: 'legal',
    name: 'Legal / Law Firm',
    slug: 'legal',
    description: 'Law firms, attorneys, and legal service providers',
    icon: 'Scale',
    categoryWeights: {
      'Business Overview': 1.3,
      'Technical Foundation': 1.0,
      'Brand & Messaging': 1.1,
      'User Experience': 1.1,
      'Traffic Readiness': 1.0,
      'Security': 1.3,
      'Content Strategy': 1.2,
      'Conversion & Engagement': 1.2,
      'Social & Multimedia': 0.5,
      'Trust & Credibility': 1.6,
    },
    focusAreas: ['Practice Areas', 'Attorney Profiles', 'Case Results', 'Free Consultation', 'Client Testimonials'],
    bestPractices: ['Clear practice area descriptions', 'Attorney credentials and experience', 'Case results (where allowed)', 'Free consultation offer', 'Professional design'],
  },
  {
    id: 'financial',
    name: 'Financial Services',
    slug: 'financial',
    description: 'Banks, financial advisors, insurance, and fintech',
    icon: 'DollarSign',
    categoryWeights: {
      'Business Overview': 1.2,
      'Technical Foundation': 1.3,
      'Brand & Messaging': 1.1,
      'User Experience': 1.3,
      'Traffic Readiness': 1.0,
      'Security': 1.6,
      'Content Strategy': 1.0,
      'Conversion & Engagement': 1.3,
      'Social & Multimedia': 0.5,
      'Trust & Credibility': 1.5,
    },
    focusAreas: ['Services Overview', 'Security Indicators', 'Regulatory Compliance', 'Calculator Tools', 'Contact Options'],
    bestPractices: ['Security certifications displayed', 'Regulatory disclosures', 'Educational content', 'Interactive calculators', 'Clear fee structures'],
  },

  // Education & Non-Profit
  {
    id: 'education',
    name: 'Education',
    slug: 'education',
    description: 'Schools, online courses, and educational institutions',
    icon: 'GraduationCap',
    categoryWeights: {
      'Business Overview': 1.2,
      'Technical Foundation': 1.2,
      'Brand & Messaging': 1.1,
      'User Experience': 1.3,
      'Traffic Readiness': 1.1,
      'Security': 1.1,
      'Content Strategy': 1.3,
      'Conversion & Engagement': 1.2,
      'Social & Multimedia': 1.0,
      'Trust & Credibility': 1.3,
    },
    focusAreas: ['Program Information', 'Enrollment Process', 'Faculty/Instructors', 'Student Outcomes', 'Campus/Platform Tour'],
    bestPractices: ['Clear program descriptions', 'Easy enrollment process', 'Instructor credentials', 'Student success stories', 'Virtual tour or preview'],
  },
  {
    id: 'non-profit',
    name: 'Non-Profit',
    slug: 'non-profit',
    description: 'Charitable organizations and non-profit entities',
    icon: 'Heart',
    categoryWeights: {
      'Business Overview': 1.3,
      'Technical Foundation': 1.0,
      'Brand & Messaging': 1.3,
      'User Experience': 1.1,
      'Traffic Readiness': 0.9,
      'Security': 1.2,
      'Content Strategy': 1.1,
      'Conversion & Engagement': 1.3,
      'Social & Multimedia': 1.0,
      'Trust & Credibility': 1.5,
    },
    focusAreas: ['Mission Statement', 'Donation Process', 'Impact Stories', 'Transparency', 'Volunteer Opportunities'],
    bestPractices: ['Clear mission and vision', 'Easy donation process', 'Impact metrics and stories', 'Financial transparency', 'Multiple ways to get involved'],
  },

  // Events & Entertainment
  {
    id: 'event',
    name: 'Event / Conference',
    slug: 'event',
    description: 'Events, conferences, festivals, and gatherings',
    icon: 'Calendar',
    categoryWeights: {
      'Business Overview': 1.2,
      'Technical Foundation': 1.1,
      'Brand & Messaging': 1.3,
      'User Experience': 1.2,
      'Traffic Readiness': 1.1,
      'Security': 1.1,
      'Content Strategy': 0.9,
      'Conversion & Engagement': 1.5,
      'Social & Multimedia': 1.2,
      'Trust & Credibility': 1.1,
    },
    focusAreas: ['Event Details', 'Speaker/Lineup', 'Ticket Purchase', 'Schedule/Agenda', 'Venue Information'],
    bestPractices: ['Clear date and location', 'Compelling speaker/performer lineup', 'Easy ticket purchase', 'Detailed schedule', 'Past event highlights'],
  },
  {
    id: 'entertainment',
    name: 'Entertainment / Media',
    slug: 'entertainment',
    description: 'Musicians, artists, podcasts, and entertainment brands',
    icon: 'Music',
    categoryWeights: {
      'Business Overview': 0.8,
      'Technical Foundation': 1.1,
      'Brand & Messaging': 1.4,
      'User Experience': 1.2,
      'Traffic Readiness': 1.0,
      'Security': 0.7,
      'Content Strategy': 1.2,
      'Conversion & Engagement': 1.1,
      'Social & Multimedia': 1.6,
      'Trust & Credibility': 0.8,
    },
    focusAreas: ['Media Showcase', 'Tour/Events', 'Merchandise', 'Social Integration', 'Fan Engagement'],
    bestPractices: ['High-quality media players', 'Tour dates and ticket links', 'Merchandise store', 'Social media feeds', 'Newsletter/fan club signup'],
  },

  // Specialized
  {
    id: 'creative-immersive',
    name: 'Creative / Immersive',
    slug: 'creative-immersive',
    description: 'High-craft creative sites with sophisticated animations, transitions, and immersive experiences',
    icon: 'Sparkles',
    categoryWeights: {
      'Business Overview': 0.5,
      'Technical Foundation': 1.0,
      'Brand & Messaging': 1.6,
      'User Experience': 1.8,
      'Traffic Readiness': 0.6,
      'Security': 0.5,
      'Content Strategy': 0.6,
      'Conversion & Engagement': 0.8,
      'Social & Multimedia': 1.4,
      'Trust & Credibility': 0.6,
    },
    focusAreas: ['Animation Quality', 'Visual Design', 'Scroll Experience', 'Motion Design', 'Art Direction', 'Interactive Elements'],
    bestPractices: ['Smooth 60fps animations', 'Purposeful motion design', 'Cohesive visual language', 'Engaging scroll interactions', 'Creative typography', 'Immersive storytelling'],
  },
  {
    id: 'landing-page',
    name: 'Landing Page',
    slug: 'landing-page',
    description: 'Single-page sites focused on a specific campaign or product',
    icon: 'Layers',
    categoryWeights: {
      'Business Overview': 0.8,
      'Technical Foundation': 1.2,
      'Brand & Messaging': 1.4,
      'User Experience': 1.3,
      'Traffic Readiness': 1.0,
      'Security': 0.8,
      'Content Strategy': 0.6,
      'Conversion & Engagement': 1.8,
      'Social & Multimedia': 0.7,
      'Trust & Credibility': 1.2,
    },
    focusAreas: ['Value Proposition', 'Single CTA Focus', 'Social Proof', 'Benefit-Driven Copy', 'Form Optimization'],
    bestPractices: ['Clear headline and value prop', 'Single focused call-to-action', 'Minimal distractions', 'Trust indicators', 'Fast load time'],
  },
  {
    id: 'government',
    name: 'Government / Public Sector',
    slug: 'government',
    description: 'Government agencies and public sector organizations',
    icon: 'Landmark',
    categoryWeights: {
      'Business Overview': 1.2,
      'Technical Foundation': 1.3,
      'Brand & Messaging': 0.8,
      'User Experience': 1.4,
      'Traffic Readiness': 1.1,
      'Security': 1.5,
      'Content Strategy': 1.1,
      'Conversion & Engagement': 0.8,
      'Social & Multimedia': 0.6,
      'Trust & Credibility': 1.3,
    },
    focusAreas: ['Services Directory', 'Accessibility', 'Contact Information', 'Forms & Documents', 'News & Updates'],
    bestPractices: ['WCAG accessibility compliance', 'Clear service navigation', 'Downloadable forms', 'Multi-language support', 'Emergency information'],
  },
  {
    id: 'documentation',
    name: 'Documentation / Knowledge Base',
    slug: 'documentation',
    description: 'Technical documentation, help centers, and knowledge bases',
    icon: 'BookOpen',
    categoryWeights: {
      'Business Overview': 0.5,
      'Technical Foundation': 1.3,
      'Brand & Messaging': 0.7,
      'User Experience': 1.5,
      'Traffic Readiness': 1.3,
      'Security': 0.8,
      'Content Strategy': 1.4,
      'Conversion & Engagement': 0.6,
      'Social & Multimedia': 0.5,
      'Trust & Credibility': 0.9,
    },
    focusAreas: ['Search Functionality', 'Content Organization', 'Code Examples', 'Version Control', 'Feedback System'],
    bestPractices: ['Powerful search', 'Clear navigation structure', 'Syntax-highlighted code', 'Version selector', 'Easy feedback mechanism'],
  },
];

// Helper functions
export function getWebsiteTypeById(id: string): WebsiteTypeConfig | undefined {
  return WEBSITE_TYPES.find((type) => type.id === id);
}

export function getWebsiteTypeBySlug(slug: string): WebsiteTypeConfig | undefined {
  return WEBSITE_TYPES.find((type) => type.slug === slug);
}

export function getActiveWebsiteTypes(): WebsiteTypeConfig[] {
  return WEBSITE_TYPES;
}

export function getCategoryWeightsForType(typeId: string): Record<string, number> {
  const type = getWebsiteTypeById(typeId);
  return type?.categoryWeights || DEFAULT_CATEGORY_WEIGHTS;
}

// Get default type (SaaS)
export function getDefaultWebsiteType(): WebsiteTypeConfig {
  return WEBSITE_TYPES.find((type) => type.id === 'saas') || WEBSITE_TYPES[0];
}
